# 'production' only prints info and above. 'development' also prints debug
environment: production
eth_rpc_url: http://localhost:8545
eth_ws_url: ws://localhost:8545
# eth_rpc_url: "http://host.docker.internal:8545"
# eth_ws_url: "ws://host.docker.internal:8545"
# address which the aggregator listens on for operator signed messages
aggregator_server_ip_port_address: localhost:8090
ecdsa_private_key_store_path: tests/keys/aggregator.ecdsa.key.json
