FROM ghcr.io/inference-labs-inc/bittensor-devcontainer:latest

ENV PATH="$PATH:/home/vscode/.ezkl"

# install foundry
RUN curl -L https://foundry.paradigm.xyz | bash
# RUN foundryup
# RUN source $HOME/.foundry/bin/foundry
