name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache UV packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/uv
          .venv
        key: ${{ runner.os }}-uv-${{ matrix.python-version }}-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-uv-${{ matrix.python-version }}-

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install dependencies
      working-directory: ./client
      run: |
        uv venv
        source .venv/bin/activate
        uv pip install -e ".[test]"

    - name: Run tests
      working-directory: ./client
      run: |
        echo "Commented out: uv run pytest tests/ -v"

    - name: Install Foundry
      run: |
        curl -L https://foundry.paradigm.xyz | bash
        echo "$HOME/.foundry/bin" >> $GITHUB_PATH
        foundryup

    - name: Run foundry
      working-directory: ./contracts
      run: |
        foundry test --no-compile --no-verify
