name: Upgrade Holesky Contracts

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed
    branches:
      - main

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: |
          cd contracts
          forge install

      - name: Build contracts
        run: |
          cd contracts
          forge build

      - name: Deploy to Holesky
        id: deploy
        env:
          PRIVATE_KEY: ${{ secrets.HOLESKY_DEPLOYER_KEY }}
          PROXY_ADMIN: ${{ vars.HOLESKY_PROXY_ADMIN }}
        run: |
          cd contracts
          SERVICE_MANAGER=$(forge script script/UpgradeHolesky.s.sol:UpgradeHolesky --rpc-url https://holesky.infura.io/v3/${{ secrets.INFURA_API_KEY }} --broadcast | grep "Service Manager Address:" | cut -d ":" -f 2 | tr -d " ")
          echo "serviceManager=$SERVICE_MANAGER" >> $GITHUB_OUTPUT

      - name: Output URLs
        run: |
          echo "Sertn AVS URL: https://holesky.eigenlayer.xyz/avs/${{ steps.deploy.outputs.serviceManager }}"
